name: React app CI-CD

env:
  CI: false

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm install

    - run: npm ci
    
    - run: touch .env
    
    - run: echo "REACT_APP_BASE_URL=${{secrets.REACT_APP_BASE_URL}}" > .env

    - run: npm run build --if-present

    - run: ls -al build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with: 
        name: build
        path: build

  deploy:
    runs-on: ubuntu-latest

    needs: [ build ]

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - run: ls -al build

    - name: Deploy build
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with: 
        username: ${{secrets.SERVER_USERNAME}}
        server: ${{secrets.SERVER_IP}}
        ssh_private_key: "${{secrets.SERVER_SSH}}"
        local_path: './build/*'
        remote_path: '/home/projects/toy-store/client'
